using WebApi_A1m.Model;

namespace WebApi_A1m.Service
{
    public class ProductoRepository : IProducto
    {
        /**/
        public static List<Producto> lstProducto =
            new List<Producto>()
        {
            new Producto(){ Id=1,titulo="Avengers: Endgame",genero_id=1,duracion=182, sinopsis="Después de que Thanos aniquiló a la mitad del universo, los Vengadores restantes se unen en un último intento de deshacer las devastadoras consecuencias del chasquido del infinito.",fechaLanzamiento="2019-04-26",precio=12.99,imagenURL="https://drive.google.com/uc?id=1vbKXrceisGYfe_Td-OPRCZevMaQe0HnX\r\n"},
            new Producto(){ Id=2,titulo="La La Land",genero_id=4,duracion=128, sinopsis="En medio del bullicio de Los Ángeles, un pianista de jazz y una aspirante a actriz se enamoran y luchan por equilibrar sus ambiciones profesionales con la creciente atracción entre ellos.",fechaLanzamiento="2016-12-09",precio=9.99,imagenURL="https://drive.google.com/uc?id=12-l1aLUpbdbREQJTj1qnudasAby0vcgX\r\n"},
            new Producto(){ Id=3,titulo="El Padrino",genero_id=1,duracion=175, sinopsis="En el mundo del crimen organizado, la familia Corleone lucha por mantener su poder mientras los enemigos y las rivalidades internas amenazan con destruir todo lo que han construido.",fechaLanzamiento="1972-03-24",precio=7.99,imagenURL="https://drive.google.com/uc?id=1CDuqSgYL12LfMohQUQ2y9-yoMvvGDuJ-\r\n"},
            new Producto(){ Id=4,titulo="El Conjuro",genero_id=5,duracion=112, sinopsis="Una pareja de investigadores paranormales se enfrenta a una aterradora presencia en una casa embrujada, desatando una serie de eventos sobrenaturales que pondrán sus vidas en peligro.",fechaLanzamiento="2013-08-02",precio=6.99,imagenURL="https://drive.google.com/uc?id=1pt9rjqMOZsdLgWAtffwd2hz5G1Bbefh7\r\n"},
            new Producto(){ Id=5,titulo="Volver al Futuro",genero_id=6,duracion=116, sinopsis="Marty McFly viaja accidentalmente en el tiempo a 1955 y debe asegurarse de que sus padres se enamoren para poder regresar al futuro, mientras evita alterar el curso de la historia.",fechaLanzamiento="1985-07-03",precio=8.99,imagenURL="https://drive.google.com/uc?id=1Ef413DqyrAKlMVmZhNxvrIlAwcuVuwWQ\r\n"},
            new Producto(){ Id=6,titulo="Buscando a Nemo",genero_id=7,duracion=100, sinopsis="Cuando el pez payaso Marlin pierde a su hijo Nemo, se embarca en una emocionante aventura por el océano para encontrarlo, enfrentándose a peligros y haciendo nuevos amigos en el camino.",fechaLanzamiento="2003-05-30",precio=5.99,imagenURL="https://drive.google.com/uc?id=1Lbw5ordgUOlX7pQTdraf2pPQmfMs_hX3\r\n"},
            new Producto(){ Id=7,titulo="Fall",genero_id=9,duracion=146, sinopsis="Para los mejores amigos Becky y Hunter, la vida se trata de conquistar miedos y superar límites. Sin embargo, después de escalar 2,000 pies hasta la cima de una torre de radio remota y abandonada, se encuentran atrapados sin forma de bajar. Ahora, sus habilidades expertas en escalada se ponen a prueba mientras luchan desesperadamente por sobrevivir a los elementos, la falta de suministros y alturas que inducen vértigo.",fechaLanzamiento="2022-08-22",precio=7.99,imagenURL="https://drive.google.com/uc?id=1mHKWVdFz2yx5e3SL68bYiG-sI_LqA0gD\r\n"},
            new Producto(){ Id=8,titulo="Titanic",genero_id=8,duracion=107, sinopsis="En el trágico viaje inaugural del RMS Titanic, un joven artista se enamora de una mujer comprometida, mientras ambos luchan por sobrevivir cuando el barco se hunde en las gélidas aguas del Atlántico.",fechaLanzamiento="1998-01-23",precio=10.99,imagenURL="https://drive.google.com/uc?id=1yQ0n8-EbFz6hA6kVYb2o0ffZVJVs35Pc\r\n"},
            new Producto(){ Id=9,titulo="La vida de Pi",genero_id=2,duracion=127, sinopsis="Después de decidir vender su zoológico en India y mudarse a Canadá, Santosh y Gita Patel abordan un barco de carga junto a sus hijos y algunos animales restantes. La tragedia golpea cuando una terrible tormenta hunde el barco, dejando al hijo adolescente de los Patel, Pi (Suraj Sharma), como el único sobreviviente humano. Sin embargo, Pi no está solo; un temible tigre de Bengala también ha encontrado refugio a bordo del bote salvavidas. A medida que los días se convierten en semanas y las semanas se arrastran en meses, Pi y el tigre deben aprender a confiar el uno en el otro si ambos quieren sobrevivir.",fechaLanzamiento="2012-12-27",precio=12.88,imagenURL="https://drive.google.com/uc?id=1yaGiQygDOQ028dU5Ens0BfFzbTKvL6i9\r\n"},
            new Producto(){ Id=10,titulo="Interestelar",genero_id=6,duracion=169, sinopsis="En un futuro donde la Tierra se está volviendo inhabitable, un grupo de astronautas se embarca en un viaje espacial en busca de un nuevo hogar para la humanidad.",fechaLanzamiento="2014-11-05",precio=10.49,imagenURL="https://drive.google.com/uc?id=1LHyC6QMSc3QEe44D09Npt2oUUlAo4B3Q\r\n"},
            new Producto(){ Id=11,titulo="Avatar: La Forma del Agua",genero_id=10,duracion=117, sinopsis="Jake, Neytiri y sus tres hijos tienen muchos problemas a los que enfrentarse, por lo que tendrán que cambiar su vida para intentar mantenerse a salvo. Por el camino, batallas que libran con antiguos enemigos y muchas tragedias.",fechaLanzamiento="2022-12-16",precio=13.12,imagenURL="https://drive.google.com/uc?id=1m3Bm01MHzzqG3gMimQZ8g3uKu924ApjX\r\n"},
            new Producto(){ Id=12,titulo="Smile",genero_id=12,duracion=118, sinopsis="Después de presenciar un incidente traumático y extraño que involucra a un paciente, la Dra. Rose Cotter comienza a experimentar sucesos aterradores que no puede explicar. A medida que un terror abrumador comienza a apoderarse de su vida, Rose debe enfrentar su problemático pasado para poder sobrevivir y escapar de su espantosa nueva realidad.",fechaLanzamiento="2022-07-30",precio=8.99,imagenURL="https://drive.google.com/uc?id=1zYPhpZ_dU4uhho7asnkGHmNKjXk2eB5g\r\n"},
            new Producto(){ Id=13,titulo="Blade Runner",genero_id=13,duracion=117, sinopsis="En un futuro distópico, un cazador de androides persigue a replicantes fugitivos en una ciudad lluviosa y oscura.",fechaLanzamiento="2017-06-25",precio=7.99,imagenURL="https://drive.google.com/uc?id=19pcmpBxeRbyYWEQneBAQbrs0G2TPjrc_\r\n"},
            new Producto(){ Id=14,titulo="El Señor de los Anillos: La Comunidad del Anillo",genero_id=6,duracion=178, sinopsis="Un joven hobbit se embarca en una aventura épica para destruir un poderoso anillo y salvar a la Tierra Media de la oscuridad.",fechaLanzamiento="2001-12-19",precio=10.99,imagenURL="https://drive.google.com/uc?id=1UbmY9jGWXDf-_yxg9BvkPMtbVIlQ4El5\r\n"},
            new Producto(){ Id=15,titulo="Bienvenidos al Wrexham",genero_id=11,duracion=154, sinopsis="En 2020, Rob y Ryan se asocian para comprar los Red Dragons de la quinta categoría con la esperanza de convertir al Wrexham Football Club en una historia de desaventajados que todo el mundo pueda apoyar. ¿El problema? Rob y Ryan no tienen experiencia en el fútbol ni trabajando juntos.",fechaLanzamiento="2022-08-22",precio=8.99,imagenURL="https://drive.google.com/uc?id=1PCbcqNPurjrjYROBXkgp6596DY2TLRSm\r\n"},
            new Producto(){ Id=16,titulo="El Rey León",genero_id=7,duracion=88, sinopsis="Un joven león debe enfrentarse a la adversidad y reclamar su lugar como rey de la sabana en esta película animada de Disney.",fechaLanzamiento="1994-06-15",precio=5.99,imagenURL="https://drive.google.com/uc?id=1_LeiGzIoPOJFXIvJJniQ3fUKKiPYZh38\r\n"},
            new Producto(){ Id=17,titulo="Forrest Gump",genero_id=3,duracion=142, sinopsis="Forrest Gump narra su extraordinaria vida llena de eventos históricos y personajes inolvidables.",fechaLanzamiento="1994-07-06",precio=8.99,imagenURL="https://drive.google.com/uc?id=1QFL97jLQ0onGotkwaKueu5oA4XeEQR9I\r\n"},
            new Producto(){ Id=18,titulo="The Super Mario Bros. Movie",genero_id=7,duracion=92, sinopsis="Mario y Luigi, dos intrépidos fontaneros, se adentran en un mundo oculto para rescatar a la Princesa Peach, secuestrada por el malvado Rey Bowser. Enfrentándose a un ejército de setas animadas y superando peligrosas rutas de ladrillos y castillos, los hermanos deberán mostrar su valentía y habilidades para cumplir su misión y salvar el reino de las garras del villano.",fechaLanzamiento="2023-04-05",precio=18.96,imagenURL="https://drive.google.com/uc?id=1GcyUDuhjCIGkbfv1OZgnwThAr1YB7BXZ\r\n"},
            new Producto(){ Id=19,titulo="Misterio a la Vista",genero_id=13,duracion=90, sinopsis="Un policía de Nueva York y su esposa van de vacaciones a Europa para revitalizar la chispa en su matrimonio. Un encuentro fortuito los lleva a ser acusados ??por el asesinato de un multimillonario anciano.",fechaLanzamiento="2019-07-14",precio=19.99,imagenURL="https://drive.google.com/uc?id=14EibFaRhyY9XsYltoxdqlqYgSlv3jdd2\r\n"},
            new Producto(){ Id=20,titulo="Free Guy",genero_id=6,duracion=115, sinopsis="Cuando un cajero de banco descubre que en realidad es un personaje secundario en un videojuego de mundo abierto, decide convertirse en el héroe de su propia historia, una que puede reescribir él mismo. En un mundo sin límites, está decidido a salvar el día a su manera antes de que sea demasiado tarde, y tal vez encontrar un poco de romance con el programador que lo concibió.",fechaLanzamiento="2021-08-13",precio=15.12,imagenURL="https://drive.google.com/uc?id=1lKL_qeQuv1qEL3X5RGv2yphlaVdCOTal\r\n"},
            new Producto(){ Id=21,titulo="La noche del Demonio",genero_id=5,duracion=103, sinopsis="Un grupo de padres (Patrick Wilson, Rose Byrne) toma medidas drásticas cuando parece que su nueva casa está siendo acosada por presencias sobrenaturales y su hijo en estado de coma está poseído por una entidad maligna.",fechaLanzamiento="2011-08-11",precio=9.22,imagenURL="https://drive.google.com/uc?id=1JMlIEQxK_tnnEl1C-EpEFXybLvIpV7oi\r\n"},
            new Producto(){ Id=22,titulo="Son como niños",genero_id=3,duracion=101, sinopsis="Un hombre soltero que bebe demasiado. Un padre con tres hijas a las que rara vez ve. Un hombre con sobrepeso y desempleado. Un marido dominado por su esposa. Un exitoso agente de Hollywood casado con una diseñadora de moda. ¿Qué tienen en común estos cinco hombres? Solían jugar en el mismo equipo de baloncesto en la escuela. Ahora su antiguo entrenador ha fallecido y se reencuentran en su funeral. ¿Podrá el grupo redescubrir viejos lazos?",fechaLanzamiento="2010-08-19",precio=8.56,imagenURL="https://drive.google.com/uc?id=1EDV31IZqaQ5nN9FDRd1TFAkfCdr0uv4w\r\n"},
            new Producto(){ Id=23,titulo="Lightyear",genero_id=7,duracion=105, sinopsis="El legendario ranger espacial Buzz Lightyear se embarca en una aventura intergaláctica junto a los ambiciosos reclutas Izzy, Mo, Darby y su compañero robot, Sox. Mientras esta disparatada tripulación enfrenta su misión más difícil hasta el momento, deben aprender a trabajar juntos como un equipo para escapar del malvado Zurg y su fiel ejército de robots, que nunca están muy lejos.",fechaLanzamiento="2022-06-17",precio=19.99,imagenURL="https://drive.google.com/uc?id=165hHO9va1w0xBYCfSfmDDTkE7vMb0fSc\r\n"},
            new Producto(){ Id=24,titulo="El niño de Pijama a Rayas",genero_id=4,duracion=94, sinopsis="Durante la Segunda Guerra Mundial, el niño de 8 años Bruno y su familia se mudan de Berlín para vivir cerca del campo de concentración donde su padre acaba de convertirse en comandante. Infeliz y solitario, un día Bruno se aventura detrás de su casa y encuentra a Shmuel, un niño judío de su edad. Aunque la cerca de alambre de púas del campo los separa, los niños comienzan una amistad prohibida, sin ser conscientes de la verdadera naturaleza de su entorno.",fechaLanzamiento="2008-09-12",precio=6.46,imagenURL="https://drive.google.com/uc?id=1kUGX2gX7MU9FDXKheTiDmBoR7iLFxQi6\r\n"},
            new Producto(){ Id=25,titulo="Uncharted\r\n",genero_id=2,duracion=116, sinopsis="El cazador de tesoros Victor \"Sully\" Sullivan recluta al astuto Nathan Drake para ayudarlo a recuperar una fortuna perdida de 500 años acumulada por el explorador Ferdinand Magellan. Lo que comienza como un robo pronto se convierte en una carrera por todo el mundo, llena de emoción y tensión, para llegar al premio antes de que el despiadado Santiago Moncada pueda ponerle las manos encima. Si Sully y Nate pueden descifrar las pistas y resolver uno de los misterios más antiguos del mundo, podrían encontrar 5 mil millones de dólares en tesoro, pero solo si aprenden a trabajar juntos.\r\n",fechaLanzamiento="2022-02-18",precio=13.25,imagenURL="https://drive.google.com/uc?id=1qnQ2MJ89IMHF9VSMD3MrGLD0fsJ-EH8X\r\n"},
            new Producto(){ Id=26,titulo="Peter Pan y Wendy",genero_id=10,duracion=106, sinopsis="Wendy Darling, una joven que busca evitar ir a un internado, conoce a Peter Pan, un niño que se niega a crecer. Wendy, sus hermanos y Campanita viajan con Peter al mágico mundo de Nunca Jamás, donde se encuentran con un malvado capitán pirata.",fechaLanzamiento="2023-04-28",precio=21.99,imagenURL="https://drive.google.com/uc?id=d8vzM5huBYnFBWOcZ-rZHysMqhYUCaNv"},
            new Producto(){ Id=27,titulo="The Black Phone",genero_id=12,duracion=142, sinopsis="Finney Shaw es un chico tímido pero inteligente de 13 años que está siendo retenido en un sótano insonorizado por un asesino sádico y enmascarado. Cuando un teléfono desconectado en la pared comienza a sonar, pronto descubre que puede escuchar las voces de las víctimas anteriores del asesino, y están decididas a asegurarse de que lo que les ocurrió a ellos no le suceda a Finney.",fechaLanzamiento="2022-06-24",precio=18.29,imagenURL="https://drive.google.com/uc?id=14U-tI16V_h1B4vv7s21Q264SIEowo3gG"},
            new Producto(){ Id=28,titulo="Ghosted",genero_id=8,duracion=116, sinopsis="Cole, un hombre sincero y trabajador, se enamora perdidamente de la enigmática Sadie, pero luego hace el sorprendente descubrimiento de que ella es una agente secreta. Antes de que puedan decidir sobre una segunda cita, Cole y Sadie se ven arrastrados a una aventura internacional para salvar el mundo.",fechaLanzamiento="2023-04-21",precio=21.78,imagenURL="https://drive.google.com/uc?id=1YmVLEzL6zF1racn2bQHmY4BiVuLUnGzk"},
            new Producto(){ Id=29,titulo="Stutz",genero_id=11,duracion=96, sinopsis="En conversaciones francas con el actor Jonah Hill, el destacado psiquiatra Phil Stutz explora sus experiencias de vida temprana y su singular modelo visual de terapia.",fechaLanzamiento="2022-11-04",precio=16.99,imagenURL="https://drive.google.com/uc?id=1perMHpx_mmnoESB9FJoppCl5QW2mQxa0"},
            new Producto(){ Id=30,titulo="La Calle Del Terror Parte 2: 1978",genero_id=9,duracion=110, sinopsis="Un verano lleno de diversión se convierte en una espeluznante lucha por la supervivencia cuando un asesino aterroriza el Campamento Nightwing en el pueblo maldito de Shadyside.",fechaLanzamiento="2021-07-08",precio=18.42,imagenURL="https://drive.google.com/uc?id=1b7oTVr3JPkJ9RkPykvpg1p-ZLqPbZ844"},
            };
        public void add(Producto obj)
        {
            lstProducto.Add(obj);
        }

        public void eliminar(int id)
        {
            lstProducto.Remove(ObtenerPorId(id));
        }

        public IEnumerable<Producto> GetAllProducts()
        {
            return lstProducto;
        }

        public void modificar(Producto objPro)
        {
            var obj = lstProducto.Where(tpro => tpro.Id == objPro.Id)
                                 .FirstOrDefault();
            obj.titulo = objPro.titulo;
            obj.genero_id = objPro.genero_id;
            obj.duracion = objPro.duracion;
            obj.sinopsis = objPro.sinopsis;
            obj.fechaLanzamiento = objPro.fechaLanzamiento;
            obj.precio = objPro.precio;
            obj.imagenURL = obj.imagenURL;
        }

        public Producto ObtenerPorId(int id)
        {
                       
            return lstProducto.Where(tpro => tpro.Id == id)
                                 .FirstOrDefault();
        }
    }
}
